# Generated by Django 3.0.2 on 2020-01-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0002_auto_20200125_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hash', models.TextField()),
                ('hash', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
