# Generated by Django 3.0.2 on 2020-01-26 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0005_auto_20200126_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='prev_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_assets', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
