# Generated by Django 3.0.2 on 2020-01-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0006_asset_prev_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
